<a href="https://colab.research.google.com/github/imran9891/TensorFlow/blob/main/00_TensorFLow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most funadamental concepts of tensors using TensorFlow

More specifically, we're going to cover:

* Introduction to Tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow(or TPUs)
* Exercise to try for yourself



## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor
                      

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Let;s try change our unchangeable tensor
# unchangeable_tensor[0] = 7
unchangeable_tensor[0].assign(7)

AttributeError: ignored

**Note:** Rarely in practice will you need to decide whether to use `tf.constant` of `tf.Variable` to create tensors, as TensorFlow does this for you. If in doubt, use `tf.constant` and change it later if needed.

### Creating Random Tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they Equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [18]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherentorder doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [20]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [21]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise:** Read through TensorFLow documentation on random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them

In [22]:
tensor_A = tf.random.Generator.from_seed(42)
tensor_A = tensor_A.normal(shape=(3,3))
tensor_A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>

In [23]:
tensor_B = tf.random.normal(shape=(3,3))
tensor_B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [24]:
tf.random.set_seed(42)
tensor_C = tf.random.normal(shape=(3,4))
tensor_C

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.2645474 ]],
      dtype=float32)>

In [25]:
tf.random.set_seed(42)
tensor_D = tf.random.normal(shape=(5,5),seed=42)
tensor_D

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.3148774 , -0.15421568,  0.91138786, -0.7991441 , -0.10875293],
       [ 0.28436786,  0.7661625 , -0.621129  ,  0.9974318 ,  0.21959257],
       [-1.0798668 , -1.9874831 ,  1.5603696 , -0.16909476, -1.3780487 ],
       [-0.29801553,  0.8410001 ,  0.9225498 , -0.48379228, -1.6971248 ],
       [ 0.09536484, -0.10675382, -1.7839274 ,  1.7145915 , -1.1761416 ]],
      dtype=float32)>

In [26]:
tensor_E = tf.constant([[1,2,3],
                        [4,5,6],
                        [7,8,9]],dtype = tf.float16)
tensor_E

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

### Shuffling all the tensors

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed.

> Rule 4: "If both the global and operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [27]:
tensor_A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>

In [28]:
tf.random.shuffle(tensor_A)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ],
       [-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [29]:
tensor_B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [30]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_B,seed=42)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [31]:
tf.random.shuffle(tensor_C)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.2645474 ],
       [ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ]],
      dtype=float32)>

In [32]:
tf.random.set_seed(20) # global level random seed
tf.random.shuffle(tensor_D,seed=23,name="I") # operation level random seed

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.0798668 , -1.9874831 ,  1.5603696 , -0.16909476, -1.3780487 ],
       [ 0.09536484, -0.10675382, -1.7839274 ,  1.7145915 , -1.1761416 ],
       [-0.29801553,  0.8410001 ,  0.9225498 , -0.48379228, -1.6971248 ],
       [ 0.28436786,  0.7661625 , -0.621129  ,  0.9974318 ,  0.21959257],
       [ 1.3148774 , -0.15421568,  0.91138786, -0.7991441 , -0.10875293]],
      dtype=float32)>

In [33]:
tf.random.shuffle(tensor_E,seed=24,name="J")

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

### Other ways to make tensors

In [34]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [35]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy Arrays into tensors

The main difference between Numpy Arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [36]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a Numpy array between 1 and 25

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [37]:
A = tf.constant(numpy_A,shape=(4,2,3,1))
A

<tf.Tensor: shape=(4, 2, 3, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15]],

        [[16],
         [17],
         [18]]],


       [[[19],
         [20],
         [21]],

        [[22],
         [23],
         [24]]]], dtype=int32)>

In [38]:
A.ndim

4

### Getting Information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [39]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [41]:
rank_4_tensor.shape,rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [42]:
# Get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of Dimensions (Rank):",rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total no. of elements in our tensor:", tf.size(rank_4_tensor))
print("Total no. of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (Rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total no. of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total no. of elements in our tensor: 120


### Indexing Tensors

Tensors can be indexed just like Python Lists.

In [43]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [44]:
# Get first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [46]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[1,2,3,4],
                             [4,5,6,7],
                             [7,8,9,10]])
rank_2_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]], dtype=int32)>

In [47]:
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([3, 4]), 2)

In [48]:
# Get the last item of each of row of our rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  7, 10], dtype=int32)>

In [49]:
# Add in extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # [:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 4, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [50]:
foo = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
print(foo[tf.newaxis, :, :])


tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)


In [51]:
print(foo[:, tf.newaxis, :])
print(foo[:, :, tf.newaxis])

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [52]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(3, 4, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [53]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations**

`+`,`-`,`*`,`/`

In [54]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10,7],[3,4]])
print(tensor + 10), print(tensor)

# Original tensor remain unchanged

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(None, None)

In [55]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [56]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [57]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [58]:
# We can use te built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [59]:
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [60]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor opertions.

Check https://matrixmultiplication.xyz

There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [61]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [62]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [63]:
# Matrix Multiplication with Python operator '@'

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [64]:
A = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])
B = tf.constant([[3,5],
                 [6,7],
                 [1,8]])
tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [65]:
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [66]:
X = tf.constant([[1,2],[3,4],[5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [67]:
Y = tf.constant([[7,8],[9,10],[11,12]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [68]:
# tf.matmul(X,Y)
X @ Y

InvalidArgumentError: ignored

**Resource:** Info and example of matrix multiplication
https://www.mathisfun.com/algebra/matrix-multiplying.html

In [69]:
# Let's change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [70]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [71]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [72]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The Dot Product**

Matrix Multiplication is also referred to as the dot Product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@ operator`

In [73]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [74]:
# Perform dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [75]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [76]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [77]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n") # "\n" is for newline

print("Y reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)),"\n")

print("Y transposed:")
print(tf.transpose(Y),end="\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you'll transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [78]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [79]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [80]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [81]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [82]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensors

Aggregating tensors = condesing them from multiple values down to a smaller amount of volumes.

In [83]:
# Get the absoluite values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [84]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [85]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([26, 32, 17, 68, 64, 39, 21, 72, 81, 76, 82, 62, 69, 77, 77, 79, 96,
       11, 52, 11, 39, 19, 37, 42, 90, 34, 33, 52, 98, 74, 71,  1,  9, 82,
       90, 94,  2, 35, 26, 58, 28, 20,  2,  0, 35, 21, 95, 72, 40, 72])>

In [86]:
tf.size(E).numpy(),E.shape, E.ndim

(50, TensorShape([50]), 1)

In [87]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [88]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [89]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [90]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2483>

**Exercise:** Find the variance and standard deviation of our `E` tensor using TensorFlow Methods

In [91]:
# Std_Deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.5>

In [92]:
# Variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=870.5>

In [93]:
# To find the variance of our tensor, we need access to tensorflow_pronbability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=870>

### Find the positional maximum and minimum


In [94]:
# Create a new tensor for finding positional mimimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# Find the positional maximum index
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [96]:
# Maximum Positional Value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [97]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [99]:
# Find the positional mimimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [100]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [101]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [102]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [103]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=(5,5))
G

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
       [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
       [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],
      dtype=float32)>

In [104]:
tf.argmax(G,axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 1, 1, 4, 4])>

In [105]:
tf.argmax(G,axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 1, 0, 0])>

In [106]:
tf.argmin(G,axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 1, 0])>

In [107]:
tf.argmin(G,axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 4, 2, 1, 2])>

### Squeezing a tensor (removing all single dimensions)

In [108]:
# Create a tensor to get started
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [109]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [110]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One Hot Encoding Tensors

In [111]:
# Create a list of indices
some_list = [0,1,2,3] # could be red,green,blue,purple

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [112]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [113]:
tf.one_hot(some_list,depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Squaring, Log, Squareroot

In [114]:
I = tf.range(1,10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [115]:
# FInd the square
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [116]:
# Find the square root
tf.sqrt(tf.cast(I,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [117]:
tf.math.log(tf.cast(I,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow interacts beautifully with Numpy arrays.

**Note:** One of the main differences between a TensorFLow tensor and a Numpy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [118]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [119]:
# Convert tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [120]:
# Convert tensor J to Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [121]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [122]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [123]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [124]:
!nvidia-smi 
# CUDA: Compute Unified Device Architecture

Sun Jun 13 20:27:31 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to CUDA-enabled GPU, TensorFLow will automatically use it whenever possible.