<a href="https://colab.research.google.com/github/imran9891/TensorFlow/blob/main/Exercies_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum val
10. One-hot encode the tensor you created in 9.

In [1]:
# Import dependencies
import tensorflow as tf

In [2]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
vector = tf.constant([1,2,3])
scalar = tf.constant(9)
matrix = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]]])
print(scalar, scalar.ndim)
print(vector, vector.ndim)
print(matrix, matrix.ndim)
print(tensor, tensor.ndim)

tf.Tensor(9, shape=(), dtype=int32) 0
tf.Tensor([1 2 3], shape=(3,), dtype=int32) 1
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 2
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32) 3


In [3]:
# 2. Find the shape, rank and size of the tensors you created in 1.
print(f"For scalar [0-dim Tensor] -> Shape: {scalar.shape}, Rank: {scalar.ndim}, Size: {tf.size(scalar)}")
print(f"For vector [1-dim Tensor] -> Shape: {vector.shape}, Rank: {vector.ndim}, Size: {tf.size(vector)}")
print(f"For matrix [2-dim Tensor] -> Shape: {matrix.shape}, Rank: {matrix.ndim}, Size: {tf.size(matrix)}")
print(f"For tensor [>=2 dim Tensor] -> Shape: {tensor.shape}, Rank: {tensor.ndim}, Size: {tf.size(tensor)}")

For scalar [0-dim Tensor] -> Shape: (), Rank: 0, Size: 1
For vector [1-dim Tensor] -> Shape: (3,), Rank: 1, Size: 3
For matrix [2-dim Tensor] -> Shape: (3, 3), Rank: 2, Size: 9
For tensor [>=2 dim Tensor] -> Shape: (2, 2, 3), Rank: 3, Size: 12


In [4]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
A = tf.random.uniform(shape=(5,300))
B = tf.random.uniform([5,300])
A,B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.8288497 , 0.3171184 , 0.3214786 , ..., 0.98938406, 0.947379  ,
         0.11432695],
        [0.65838945, 0.57755065, 0.00991213, ..., 0.22210336, 0.6553812 ,
         0.2341336 ],
        [0.04907262, 0.7175987 , 0.09784639, ..., 0.5993694 , 0.33852625,
         0.3620057 ],
        [0.03349459, 0.4203334 , 0.3297844 , ..., 0.94915295, 0.13377702,
         0.43055964],
        [0.4404608 , 0.82453835, 0.6691748 , ..., 0.5822307 , 0.26620448,
         0.08346176]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.9354037 , 0.08118522, 0.47155607, ..., 0.5774158 , 0.7473916 ,
         0.5185745 ],
        [0.4585644 , 0.59032345, 0.74393964, ..., 0.17758846, 0.5009464 ,
         0.19005692],
        [0.42583907, 0.5460187 , 0.6551306 , ..., 0.5806395 , 0.6889794 ,
         0.98990357],
        [0.06310368, 0.2504704 , 0.09860694, ..., 0.25135076, 0.21399295,
         0.4560244 ],
        [0.40147

In [5]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.65474 , 75.62619 , 73.73378 , 71.762115, 77.142685],
       [74.25544 , 74.93011 , 75.01372 , 71.425   , 70.54549 ],
       [71.04306 , 76.43445 , 71.666534, 72.84872 , 69.9235  ],
       [70.81137 , 74.953995, 71.43256 , 67.966896, 71.910774],
       [71.897156, 73.8784  , 74.36272 , 70.61011 , 70.31136 ]],
      dtype=float32)>

In [6]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(A,tf.transpose(B),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.65474 , 75.62619 , 73.73378 , 71.762115, 77.142685],
       [74.25544 , 74.93011 , 75.01372 , 71.425   , 70.54549 ],
       [71.04306 , 76.43445 , 71.666534, 72.84872 , 69.9235  ],
       [70.81137 , 74.953995, 71.43256 , 67.966896, 71.910774],
       [71.897156, 73.8784  , 74.36272 , 70.61011 , 70.31136 ]],
      dtype=float32)>

In [7]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
C = tf.random.uniform([224,224,3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.13529837, 0.14589465, 0.35807002],
        [0.68750405, 0.44659185, 0.11544669],
        [0.7690625 , 0.9764967 , 0.28665078],
        ...,
        [0.8532376 , 0.23192573, 0.7609869 ],
        [0.04588461, 0.12690866, 0.1504432 ],
        [0.6545272 , 0.6337098 , 0.07519782]],

       [[0.60329175, 0.17034233, 0.6725229 ],
        [0.63967323, 0.29928327, 0.30300057],
        [0.31982124, 0.19604552, 0.40567076],
        ...,
        [0.11984158, 0.97637606, 0.46269464],
        [0.56224096, 0.8759949 , 0.32535362],
        [0.08426952, 0.1936984 , 0.99245346]],

       [[0.15535045, 0.05195439, 0.09659839],
        [0.7407373 , 0.05489051, 0.5721164 ],
        [0.56122816, 0.24509645, 0.6885805 ],
        ...,
        [0.91780233, 0.88189673, 0.6902509 ],
        [0.2081877 , 0.2409575 , 0.4420241 ],
        [0.76845205, 0.5106441 , 0.3441844 ]],

       ...,

       [[0.8254609 , 0.73941255, 0.84233   ],
        [0.89

In [8]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.
min = tf.reduce_min(C)
max = tf.reduce_max(C)
min,max

(<tf.Tensor: shape=(), dtype=float32, numpy=7.1525574e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999969>)

In [9]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
D = tf.random.uniform([1,224,224,3])
print("Shape before squeeze: ",D.shape)
D = tf.squeeze(D)
print("Shape after squeeze: ",D.shape)
D

Shape before squeeze:  (1, 224, 224, 3)
Shape after squeeze:  (224, 224, 3)


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.19269669, 0.9710702 , 0.63114333],
        [0.01074171, 0.94361544, 0.17753386],
        [0.3304187 , 0.803671  , 0.56820774],
        ...,
        [0.3158034 , 0.34741855, 0.8221456 ],
        [0.23812306, 0.36464107, 0.7125269 ],
        [0.6367663 , 0.79966176, 0.77721727]],

       [[0.5375104 , 0.01122999, 0.93686116],
        [0.90038574, 0.4899844 , 0.7717763 ],
        [0.9998174 , 0.49367046, 0.42074454],
        ...,
        [0.5429026 , 0.65494907, 0.6754477 ],
        [0.63660455, 0.00681758, 0.26665545],
        [0.5210124 , 0.00755978, 0.45459342]],

       [[0.79587376, 0.8917445 , 0.6216935 ],
        [0.144521  , 0.5775783 , 0.37520623],
        [0.01748526, 0.49371862, 0.6815995 ],
        ...,
        [0.40729892, 0.7410337 , 0.4405073 ],
        [0.27947748, 0.64469326, 0.47807372],
        [0.95677257, 0.56568813, 0.9113041 ]],

       ...,

       [[0.62399495, 0.788028  , 0.32096446],
        [0.12

In [10]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum val
E = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(E.shape)
index = tf.argmax(E)
index

(10,)


<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [11]:
# 10. One-hot encode the tensor you created in 9.
one_hot_F = tf.one_hot(E,depth=10)
one_hot_F

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

* Basics of TensorFLow: https://www.tensorflow.org/api_docs/python/tf/all_symbols
* Quickstart for beginners: https://www.tensorflow.org/tutorials/quickstart/beginner
* Tensor Video: https://www.youtube.com/watch?v=f5liqUk0ZTw